# Generated by Django 5.2.5 on 2025-09-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_reviews_comments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
    ]
