# Generated by Django 5.2.8 on 2025-11-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_comments_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Текст обзора'),
        ),
    ]
